base: &base

  # Model config
  embed_dim: 384
  depth: 12
  dropout: 0.0
  patch_size: 8
  num_heads: 8

  # Training config
  img_size: [360, 720]
  dt: 1 
  global_batch_size: 16 # number of samples per training batch
  num_iters: 30000
  amp_mode: none
  enable_fused: false
  enable_jit: false
  expdir: './logs'
  lr_schedule: 'cosine'
  lr: 5E-4
  warmup: 0
  optimizer: 'Adam'

  # Data
  data_loader_config: 'pytorch'
  num_data_workers: 0 # number of dataloader worker threads per proc
  n_in_channels: 20
  n_out_channels: 20
  train_data_path:   '/lustre/orion/world-shared/stf218/junqi/data/EAR5/train'
  valid_data_path:   '/lustre/orion/world-shared/stf218/junqi/data/EAR5/valid'
  inf_data_path:     '/lustre/orion/world-shared/stf218/junqi/data/EAR5/test'
  time_means_path:   '/lustre/orion/world-shared/stf218/junqi/data/EAR5/stats/time_means.npy'
  global_means_path: '/lustre/orion/world-shared/stf218/junqi/data/EAR5/stats/global_means.npy'
  global_stds_path:  '/lustre/orion/world-shared/stf218/junqi/data/EAR5/stats/global_stds.npy'
  limit_nsamples: None
  limit_nsamples_val: None

  # Comms
  wireup_info: env
  wireup_store: tcp

mp: &mp
  <<: *base
  num_iters: 10
  eval_steps: 20 
  print_steps: 2 
  save_path: "./checkpoints"
  patch_size: 8
  attn_type: "megatron"
  global_batch_size: 512
  lr: 1e-3
  num_data_workers: 2
  data_loader_config: 'pytorch'
  amp_mode: bf16
  enable_jit: true
  enable_fused: true

mp_emb384: &mp_emb384
  <<: *mp
  embed_dim: 384
  num_heads: 4
  global_batch_size: 32

mp_emb768: &mp_emb768
  <<: *mp
  embed_dim: 768
  num_heads: 8
  global_batch_size: 16  
  
mp_emb1024: &mp_emb1024
  <<: *mp
  embed_dim: 1024
  num_heads: 8 
  global_batch_size: 8

mp_emb2048: &mp_emb2048
  <<: *mp
  embed_dim: 2048
  num_heads: 16 
  global_batch_size: 4

mp_emb4096: &mp_emb4096
  <<: *mp
  embed_dim: 4096
  num_heads: 32
  global_batch_size: 1
